insert into clinics (slug, name, city, country, region, categories, price_min, price_max, currency, rating, review_count, verified, premium, languages, description, website_url, contact_url, address, phone, founded_year) values

('london-mens-health-london', 'London Men''s Health', 'London', 'United Kingdom', 'EU', ARRAY['trt','ed','pe'], 1800, 3500, 'EUR', 4.7, 142, true, true, ARRAY['English'], 'Premier men''s health clinic in central London offering comprehensive testosterone replacement therapy, erectile dysfunction treatment and premature ejaculation solutions. Our team of experienced urologists and endocrinologists provides discreet, evidence-based care tailored to each patient.', 'https://londonmenshealth.example.com', 'https://londonmenshealth.example.com/contact', '47 Harley Street, London W1G 8QD', '+44 20 7946 0100', 2015),

('munich-male-clinic-munich', 'Munich Male Clinic', 'Munich', 'Germany', 'EU', ARRAY['penis_filler','trt','fertility'], 2200, 5500, 'EUR', 4.6, 89, true, true, ARRAY['German','English'], 'Specialised men''s health centre in Munich offering penile enhancement procedures, hormone optimisation and male fertility treatments. State-of-the-art facilities with German precision and discretion.', 'https://munichmaleclinic.example.com', 'https://munichmaleclinic.example.com/contact', 'Maximilianstraße 35, 80539 München', '+49 89 2104 7700', 2017),

('paris-clinic-homme-paris', 'Clinique Homme Paris', 'Paris', 'France', 'EU', ARRAY['penis_filler','ed'], 2000, 4800, 'EUR', 4.4, 67, true, false, ARRAY['French','English'], 'Boutique men''s aesthetic and sexual health clinic in Paris. We specialise in penile enhancement with HA fillers and comprehensive erectile dysfunction management using the latest shockwave therapy protocols.', 'https://cliniquehomme.example.com', 'https://cliniquehomme.example.com/contact', '12 Rue du Faubourg Saint-Honoré, 75008 Paris', '+33 1 4266 9100', 2018),

('warsaw-mens-clinic-warsaw', 'Warsaw Men''s Clinic', 'Warsaw', 'Poland', 'EU', ARRAY['penis_filler','trt','ed'], 700, 1800, 'EUR', 4.5, 211, true, true, ARRAY['Polish','English','Russian'], 'Leading men''s health clinic in Warsaw providing affordable penile enhancement, TRT programmes and ED treatment. Internationally trained doctors, competitive European pricing and full discretion guaranteed.', 'https://warsawmensclinic.example.com', 'https://warsawmensclinic.example.com/contact', 'ul. Nowy Świat 64, 00-357 Warszawa', '+48 22 828 4400', 2016),

('prague-andrology-prague', 'Prague Andrology Centre', 'Prague', 'Czech Republic', 'EU', ARRAY['penis_filler','ed','pe'], 750, 2000, 'EUR', 4.3, 158, true, false, ARRAY['Czech','English','German'], 'Comprehensive andrology centre in Prague''s medical district. Full spectrum of men''s sexual health services at central European prices with English-speaking staff and EU-standard care.', 'https://pragueandrology.example.com', 'https://pragueandrology.example.com/contact', 'Náměstí Republiky 3, 110 00 Praha 1', '+420 221 614 800', 2014),

('budapest-mens-health-budapest', 'Budapest Men''s Health Institute', 'Budapest', 'Hungary', 'EU', ARRAY['trt','ed','fertility'], 600, 1600, 'EUR', 4.2, 94, false, false, ARRAY['Hungarian','English'], 'Affordable men''s health care in Budapest. Hormone therapy, ED treatment and fertility evaluation from specialist urologists. Popular destination for medical tourism from Western Europe.', 'https://budapestmenshealth.example.com', 'https://budapestmenshealth.example.com/contact', 'Andrássy út 22, 1061 Budapest', '+36 1 374 4200', 2019),

('istanbul-aesthetic-men-istanbul', 'Istanbul Aesthetic Men', 'Istanbul', 'Turkey', 'EU', ARRAY['penis_filler','trt','ed'], 500, 1400, 'EUR', 4.6, 384, true, true, ARRAY['Turkish','English','Arabic'], 'Istanbul''s premier men''s enhancement clinic. Renowned for competitive pricing, high procedure volumes and experienced surgical teams. Penile enhancement, TRT and ED protocols that meet international standards.', 'https://istanbulaestheticmen.example.com', 'https://istanbulaestheticmen.example.com/contact', 'Bağdat Caddesi 349, Kadıköy, Istanbul', '+90 216 414 7500', 2013),

('amsterdam-mens-clinic-amsterdam', 'Amsterdam Men''s Clinic', 'Amsterdam', 'Netherlands', 'EU', ARRAY['trt','ed','pe','fertility'], 1600, 3800, 'EUR', 4.5, 112, true, false, ARRAY['Dutch','English','German'], 'Progressive men''s health clinic in Amsterdam. Integrative approach combining hormone optimisation, sexual health treatment and fertility support. Open-minded, non-judgmental care environment.', 'https://amsterdammens.example.com', 'https://amsterdammens.example.com/contact', 'Keizersgracht 394, 1016 GB Amsterdam', '+31 20 638 9200', 2016),

('barcelona-instituto-masculino-barcelona', 'Instituto Masculino Barcelona', 'Barcelona', 'Spain', 'EU', ARRAY['penis_filler','ed','pe'], 900, 2600, 'EUR', 4.4, 176, true, false, ARRAY['Spanish','Catalan','English'], 'Specialist men''s aesthetic and sexual health institute in Barcelona. Expert penile enhancement with certified injectors and multidisciplinary ED and PE treatment pathways.', 'https://institutomasculino.example.com', 'https://institutomasculino.example.com/contact', 'Passeig de Gràcia 85, 08008 Barcelona', '+34 93 272 3100', 2017),

('lisbon-mens-health-lisbon', 'Lisbon Men''s Health', 'Lisbon', 'Portugal', 'EU', ARRAY['trt','fertility'], 800, 2200, 'EUR', 4.1, 43, false, false, ARRAY['Portuguese','English'], 'Men''s health specialist clinic in Lisbon offering hormone replacement programmes and male fertility workups. Experienced endocrinology team with a modern, discreet practice environment.', 'https://lisbonmenshealth.example.com', 'https://lisbonmenshealth.example.com/contact', 'Avenida da Liberdade 110, 1269-046 Lisboa', '+351 21 310 4400', 2020),

('tallinn-nordic-mens-tallinn', 'Nordic Men''s Clinic Tallinn', 'Tallinn', 'Estonia', 'EU', ARRAY['trt','ed'], 900, 2400, 'EUR', 4.3, 61, true, false, ARRAY['Estonian','English','Finnish'], 'Nordic-standard men''s health clinic in Tallinn. Testosterone replacement therapy and ED treatment for both local and visiting patients. Efficient digital-first booking and follow-up system.', 'https://nordicmensclinic.example.com', 'https://nordicmensclinic.example.com/contact', 'Viru väljak 4, 10111 Tallinn', '+372 6623 800', 2018),

('stockholm-karolinska-mens-stockholm', 'Karolinska Men''s Health', 'Stockholm', 'Sweden', 'EU', ARRAY['trt','fertility','pe'], 2200, 5000, 'EUR', 4.8, 97, true, true, ARRAY['Swedish','English'], 'Premium men''s health centre affiliated with Stockholm''s medical community. Evidence-based TRT protocols, male fertility specialisation and premature ejaculation treatment by senior clinicians.', 'https://karolinskamens.example.com', 'https://karolinskamens.example.com/contact', 'Stureplan 4C, 114 35 Stockholm', '+46 8 611 2300', 2012),

('helsinki-men-clinic-helsinki', 'Helsinki Men Clinic', 'Helsinki', 'Finland', 'EU', ARRAY['trt','ed','fertility'], 1900, 4200, 'EUR', 4.6, 78, true, false, ARRAY['Finnish','Swedish','English'], 'Comprehensive men''s health clinic in Helsinki. Hormone therapy, erectile dysfunction and fertility services delivered by specialist urologists and endocrinologists.', 'https://helsinkimenclinic.example.com', 'https://helsinkimenclinic.example.com/contact', 'Pohjoisesplanadi 33, 00100 Helsinki', '+358 9 6121 4400', 2015),

('riga-baltic-mens-riga', 'Baltic Men''s Health Riga', 'Riga', 'Latvia', 'EU', ARRAY['penis_filler','trt','ed'], 650, 1700, 'EUR', 4.0, 52, false, false, ARRAY['Latvian','Russian','English'], 'Affordable men''s health services in Riga. Penile enhancement procedures, TRT consultations and ED treatment at Baltic prices. Convenient for visitors from Scandinavia and the UK.', 'https://balticmenshealth.example.com', 'https://balticmenshealth.example.com/contact', 'Brīvības iela 40, Rīga, LV-1050', '+371 6720 2800', 2019),

('zurich-swiss-mens-clinic-zurich', 'Swiss Men''s Clinic Zürich', 'Zürich', 'Switzerland', 'EU', ARRAY['penis_filler','trt','ed','pe','fertility'], 3500, 8500, 'EUR', 4.9, 63, true, true, ARRAY['German','French','English'], 'Switzerland''s most comprehensive men''s health clinic. All five service categories under one roof in Zürich. Premium facilities, exceptional discretion and the highest clinical standards in Europe.', 'https://swissmenscliniic.example.com', 'https://swissmenscliniic.example.com/contact', 'Bahnhofstrasse 69, 8001 Zürich', '+41 44 211 4500', 2011),

('bangkok-mens-health-center-bangkok', 'Bangkok Men''s Health Center', 'Bangkok', 'Thailand', 'World', ARRAY['penis_filler','ed','pe'], 350, 900, 'EUR', 4.5, 467, true, true, ARRAY['Thai','English'], 'Leading men''s health destination in Bangkok''s medical tourism hub. Internationally accredited clinic offering penile enhancement and sexual health treatment at a fraction of European prices with no compromise on quality.', 'https://bangkokmenshealthcenter.example.com', 'https://bangkokmenshealthcenter.example.com/contact', 'Sukhumvit Road, Soi 3, Watthana, Bangkok 10110', '+66 2 651 7800', 2014),

('dubai-elite-mens-dubai', 'Elite Men''s Clinic Dubai', 'Dubai', 'UAE', 'World', ARRAY['trt','penis_filler','ed'], 1200, 3200, 'EUR', 4.7, 203, true, true, ARRAY['English','Arabic'], 'Dubai''s foremost men''s health and enhancement clinic. Serving the Gulf''s professional community with world-class TRT programmes, penile enhancement and ED treatment in a discreet, luxury environment.', 'https://elitemensdubai.example.com', 'https://elitemensdubai.example.com/contact', 'Dubai Healthcare City, Building 27, Dubai', '+971 4 362 7700', 2016),

('singapore-mens-health-singapore', 'Singapore Men''s Health Specialists', 'Singapore', 'World', ARRAY['trt','ed','fertility'], 1400, 3600, 'EUR', 4.6, 134, true, false, ARRAY['English','Mandarin','Malay'], 'Singapore''s trusted men''s health specialists. Hormone therapy, sexual function and fertility services for expats and local professionals. International standards, English-first care.', 'https://sgmenshealth.example.com', 'https://sgmenshealth.example.com/contact', '290 Orchard Road, #14-10 Paragon, Singapore 238859', '+65 6733 4400', 2015),

('chiang-mai-renewal-mens-chiang-mai', 'Renewal Men''s Clinic Chiang Mai', 'Chiang Mai', 'Thailand', 'World', ARRAY['trt','pe','fertility'], 300, 800, 'EUR', 4.2, 89, false, false, ARRAY['Thai','English'], 'Boutique men''s health clinic in Chiang Mai offering TRT, premature ejaculation treatment and fertility consultations. Popular with long-stay expats seeking quality care at Thai prices.', 'https://renewalmenscm.example.com', 'https://renewalmenscm.example.com/contact', 'Nimman Road 17, Suthep, Muang, Chiang Mai 50200', '+66 53 894 600', 2020),

('gdansk-baltic-andrology-gdansk', 'Baltic Andrology Gdańsk', 'Gdańsk', 'Poland', 'EU', ARRAY['ed','pe','fertility'], 600, 1500, 'EUR', 4.1, 74, false, false, ARRAY['Polish','English'], 'Specialist andrology clinic in Gdańsk. ED shockwave therapy, PE treatment and complete male fertility evaluation. Cost-effective alternative to Western European clinics.', 'https://balticandrology.example.com', 'https://balticandrology.example.com/contact', 'ul. Długa 47, 80-827 Gdańsk', '+48 58 301 8800', 2018),

('berlin-mannclinic-berlin', 'MannClinic Berlin', 'Berlin', 'Germany', 'EU', ARRAY['ed','pe','trt'], 1700, 4000, 'EUR', 4.4, 156, true, false, ARRAY['German','English'], 'Contemporary men''s health clinic in Berlin Mitte. Shockwave ED therapy, TRT and premature ejaculation specialist consultations. Evidence-based protocols, transparent pricing.', 'https://mannclinic.example.com', 'https://mannclinic.example.com/contact', 'Unter den Linden 38, 10117 Berlin', '+49 30 2094 7700', 2016),

('valencia-clinica-masculina-valencia', 'Clínica Masculina Valencia', 'Valencia', 'Spain', 'EU', ARRAY['penis_filler','fertility'], 850, 2400, 'EUR', 3.9, 38, false, false, ARRAY['Spanish','English'], 'Men''s aesthetic and fertility clinic in Valencia. Penile enhancement with experienced practitioners and full male fertility workup service. Warm Mediterranean approach to men''s health.', 'https://clinicamasculina.example.com', 'https://clinicamasculina.example.com/contact', 'Carrer de Colom 12, 46004 Valencia', '+34 96 310 4400', 2021),

('pattaya-intl-mens-pattaya', 'Pattaya International Men''s Clinic', 'Pattaya', 'Thailand', 'World', ARRAY['penis_filler','ed'], 380, 950, 'EUR', 4.3, 312, true, false, ARRAY['Thai','English','Russian'], 'International men''s health clinic in Pattaya. High-volume penile enhancement and ED treatment facility serving medical tourists from Europe, Russia and Australia. JCIA-aligned protocols.', 'https://pattayaimensclinic.example.com', 'https://pattayaimensclinic.example.com/contact', 'Beach Road 219, Pattaya City, Chonburi 20150', '+66 38 710 5500', 2015),

('edinburgh-mens-health-edinburgh', 'Edinburgh Men''s Health', 'Edinburgh', 'United Kingdom', 'EU', ARRAY['trt','ed','fertility'], 1600, 3200, 'EUR', 4.5, 88, true, false, ARRAY['English'], 'Dedicated men''s health clinic in Edinburgh''s New Town. Hormone therapy, erectile dysfunction and fertility evaluation delivered by GMC-registered specialists. Serving Scotland and northern England.', 'https://edinburghmenshealth.example.com', 'https://edinburghmenshealth.example.com/contact', '28 Queen Street, Edinburgh EH2 1JX', '+44 131 220 4400', 2017),

('abu-dhabi-mens-wellness-abu-dhabi', 'Abu Dhabi Men''s Wellness', 'Abu Dhabi', 'UAE', 'World', ARRAY['trt','fertility'], 1100, 2800, 'EUR', 4.2, 57, false, false, ARRAY['English','Arabic'], 'Men''s wellness clinic in Abu Dhabi serving UAE nationals, expats and medical tourists. Comprehensive TRT programmes and male fertility services in a discreet, professional environment.', 'https://abudhabimenswellness.example.com', 'https://abudhabimenswellness.example.com/contact', 'Al Muroor Road, Sector E-11/4, Abu Dhabi', '+971 2 441 9900', 2019),

('krakow-centrum-andrologii-krakow', 'Centrum Andrologii Kraków', 'Kraków', 'Poland', 'EU', ARRAY['penis_filler','pe','ed'], 680, 1900, 'EUR', 4.4, 127, true, false, ARRAY['Polish','English'], 'Premier andrology centre in Kraków. Penile enhancement procedures, PE treatment and ED therapy from board-certified andrologists. Excellent value for international patients visiting southern Poland.', 'https://centrumandrologiikrakow.example.com', 'https://centrumandrologiikrakow.example.com/contact', 'ul. Floriańska 31, 31-019 Kraków', '+48 12 421 7700', 2016);
